// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBociTBs1l0zpPC8a9NGUK2yYWJM2cKDno',
    appId: '1:981298730892:web:a670152c7386960d8ae8a9',
    messagingSenderId: '981298730892',
    projectId: 'todo-app-flutter-492ef',
    authDomain: 'todo-app-flutter-492ef.firebaseapp.com',
    storageBucket: 'todo-app-flutter-492ef.appspot.com',
    measurementId: 'G-B2CZT9HQFW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDOwK53LfhBe8Lz2MjAmdWUWrV1DRlNaA',
    appId: '1:981298730892:android:2fded0c9849648d78ae8a9',
    messagingSenderId: '981298730892',
    projectId: 'todo-app-flutter-492ef',
    storageBucket: 'todo-app-flutter-492ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZL0nwxBbhucMAhJ14Uu2npN-_0szSYJw',
    appId: '1:981298730892:ios:e2bdb98aa9f29b3b8ae8a9',
    messagingSenderId: '981298730892',
    projectId: 'todo-app-flutter-492ef',
    storageBucket: 'todo-app-flutter-492ef.appspot.com',
    iosClientId:
        '981298730892-469hit526ls1bhe2lrp87g4ga1g6osk9.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZL0nwxBbhucMAhJ14Uu2npN-_0szSYJw',
    appId: '1:981298730892:ios:b25b377f1965255a8ae8a9',
    messagingSenderId: '981298730892',
    projectId: 'todo-app-flutter-492ef',
    storageBucket: 'todo-app-flutter-492ef.appspot.com',
    iosClientId:
        '981298730892-v5a0ufosntfck38nuts1bhmstoaqojnh.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
